# Generated by Django 4.2.27 on 2025-12-31 14:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='科目代碼')),
                ('name', models.CharField(max_length=100, verbose_name='科目名稱')),
                ('account_type', models.CharField(choices=[('ASSET', '資產'), ('LIABILITY', '負債'), ('EQUITY', '權益'), ('REVENUE', '收入'), ('EXPENSE', '費用')], max_length=10, verbose_name='科目類別')),
                ('is_control', models.BooleanField(default=False, verbose_name='統制帳戶')),
                ('description', models.TextField(blank=True, null=True, verbose_name='科目說明')),
            ],
            options={
                'verbose_name': '會計科目',
                'verbose_name_plural': '會計科目列表',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='傳票日期')),
                ('description', models.CharField(max_length=255, verbose_name='傳票摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後修改')),
            ],
            options={
                'verbose_name': '傳票主檔',
                'verbose_name_plural': '傳票列表',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='明細摘要')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='借方金額')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='貸方金額')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='會計科目')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.journalentry', verbose_name='所屬傳票')),
            ],
            options={
                'verbose_name': '傳票明細',
                'verbose_name_plural': '傳票明細',
            },
        ),
    ]
